# Yuhe Wu
# week11: 2021/11/04 - 2021/11/09
# python numpy universal functions

In [1]:
# zip()

import numpy as np

lst1 = [1,2,3,4,5,6,7,8,9]
lst2 = [11,12,13,14,15,16,17,18,19]

z = list(zip(lst1,lst2))
z

[(1, 11),
 (2, 12),
 (3, 13),
 (4, 14),
 (5, 15),
 (6, 16),
 (7, 17),
 (8, 18),
 (9, 19)]

In [2]:
z = []

for i,j in zip(lst1,lst2):
    z.append(i + j)
    
z

[12, 14, 16, 18, 20, 22, 24, 26, 28]

In [3]:
fname = ("Alice", "Bob", "Christy")
lname = ("Charlie", "Clark", "Robert")

flname = zip(fname,lname)
print(tuple(flname))

(('Alice', 'Charlie'), ('Bob', 'Clark'), ('Christy', 'Robert'))


In [4]:
arr = np.arange(21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [5]:
# sqrt
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [6]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08])

In [7]:
# randn
arr1 = np.random.randn(10)
arr1

array([-1.43817531,  0.8584167 , -0.4286676 ,  0.26511238,  1.01634558,
       -0.34309165, -1.90803897, -0.15676311,  0.59577163,  1.52083566])

In [8]:
arr2 = np.random.randn(10)
arr2

array([ 1.18876169,  0.06908754,  0.58566555, -0.28005267, -1.03744155,
       -0.30170333,  0.23375734, -0.91570097,  0.21142203,  1.39465865])

In [9]:
np.add(arr1,arr2)

array([-0.24941362,  0.92750424,  0.15699796, -0.01494029, -0.02109596,
       -0.64479498, -1.67428163, -1.07246409,  0.80719366,  2.91549432])

In [10]:
np.maximum(arr1,arr2)

array([ 1.18876169,  0.8584167 ,  0.58566555,  0.26511238,  1.01634558,
       -0.30170333,  0.23375734, -0.15676311,  0.59577163,  1.52083566])

In [11]:
arr1 = np.arange(9).reshape(3,3)
arr2 = np.ones(9).reshape(3,3)

In [12]:
print(arr1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
print(arr2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
np.add(arr1,arr2)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [15]:
# array filtering
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
print(arr > 4)

[[False False False]
 [False False  True]
 [ True  True  True]]


In [17]:
# using where

np.where(arr < 4, 0,1)

array([[0, 0, 0],
       [0, 1, 1],
       [1, 1, 1]])

In [18]:
np.where((arr < 4) & (arr > 2), 0,1)

array([[1, 1, 1],
       [0, 1, 1],
       [1, 1, 1]])

In [19]:
arr1 = np.array([1,2,3,4,5])
arr2 = arr1 * 10

arr_b = np.array([True,False,True,True,False])

print(arr1)
print(arr2)
print(arr_b)
print(list(zip(arr1,arr2,arr_b)))

[1 2 3 4 5]
[10 20 30 40 50]
[ True False  True  True False]
[(1, 10, True), (2, 20, False), (3, 30, True), (4, 40, True), (5, 50, False)]


In [20]:
# using list comprehension

arr3 = [r1 if c else r2 for r1,r2,c in zip(arr1,arr2,arr_b)]

arr3

[1, 20, 3, 4, 50]

In [21]:
# using where 
arr3 = np.where(arr_b,arr1,arr2)
arr3

array([ 1, 20,  3,  4, 50])

In [22]:
# 2-D
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
cond = np.array([[True,False],[True,True]])

print(arr1,"\n\n",arr2,"\n\n",cond)

[[1 2]
 [3 4]] 

 [[5 6]
 [7 8]] 

 [[ True False]
 [ True  True]]


In [23]:
arr3 = np.where(cond,arr1,arr2)

In [24]:
arr3

array([[1, 6],
       [3, 4]])

In [25]:
arr = np.random.randn(3,3)
arr

array([[-0.89484073, -0.28947349,  0.61329131],
       [-0.5871181 ,  0.83859074, -1.43484518],
       [-0.23241692, -0.38795069, -0.235323  ]])

In [26]:
np.where(arr<0,0,arr)

array([[0.        , 0.        , 0.61329131],
       [0.        , 0.83859074, 0.        ],
       [0.        , 0.        , 0.        ]])

In [28]:
arr_b = np.array([True,False,True,False,False])
arr_b.any()

True

In [29]:
arr_b.all()

False

In [30]:
fruits = np.array(['Apple','Cherry','Apple','Orange','Cherry','Banana'])
fruits

array(['Apple', 'Cherry', 'Apple', 'Orange', 'Cherry', 'Banana'],
      dtype='<U6')

In [31]:
np.unique(fruits)

array(['Apple', 'Banana', 'Cherry', 'Orange'], dtype='<U6')

In [32]:
np.in1d(['Apple','Cherry','Grape'], fruits)

array([ True,  True, False])

In [33]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr.shape

(3, 3)

In [34]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
arr.sum()

45

In [36]:
arr.sum(0) #y

array([12, 15, 18])

In [37]:
arr.sum(1) #x

array([ 6, 15, 24])

In [38]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [39]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [40]:
np.sum(arr,axis=None)

45

In [41]:
arr.mean()

5.0

In [42]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
arr.mean(0)

array([4., 5., 6.])

In [44]:
arr.mean(1)

array([2., 5., 8.])

In [45]:
np.mean(arr,axis=0)

array([4., 5., 6.])

In [46]:
np.mean(arr,axis=1)

array([2., 5., 8.])

In [47]:
np.mean(arr,axis=None)

5.0

In [48]:
arr.var()

6.666666666666667

In [49]:
arr.std()

2.581988897471611

In [52]:
arr = np.array([3,4,5,2,1,3,6,7,5,6,8,9])
arr

array([3, 4, 5, 2, 1, 3, 6, 7, 5, 6, 8, 9])

In [53]:
arr.sort()
arr

array([1, 2, 3, 3, 4, 5, 5, 6, 6, 7, 8, 9])

In [55]:
# identity array
i = np.eye(5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [59]:
a = np.arange(25).reshape((5,5))

In [57]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [60]:
a*i

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  6.,  0.,  0.,  0.],
       [ 0.,  0., 12.,  0.,  0.],
       [ 0.,  0.,  0., 18.,  0.],
       [ 0.,  0.,  0.,  0., 24.]])

In [62]:
arr = np.arange(1,9).reshape(2,4)
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [63]:
arr.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [64]:
arr.shape

(2, 4)

In [65]:
arr.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [66]:
arr.transpose((0,1))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [67]:
arr.transpose((1,0))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [68]:
arr_3d = np.arange(20).reshape(2,5,2)
arr_3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [73]:
arr_3d.shape

(2, 5, 2)

In [74]:
arr_3d.transpose((0,1,2))   #transpose based on the shape 

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [71]:
arr_3d.transpose((0,2,1))

array([[[ 0,  2,  4,  6,  8],
        [ 1,  3,  5,  7,  9]],

       [[10, 12, 14, 16, 18],
        [11, 13, 15, 17, 19]]])

In [72]:
arr_3d.transpose((1,0,2))

array([[[ 0,  1],
        [10, 11]],

       [[ 2,  3],
        [12, 13]],

       [[ 4,  5],
        [14, 15]],

       [[ 6,  7],
        [16, 17]],

       [[ 8,  9],
        [18, 19]]])

In [76]:
np.random.random((4,4))

array([[0.54317598, 0.83714293, 0.909604  , 0.22421708],
       [0.13372419, 0.50898652, 0.03899765, 0.25231826],
       [0.78613755, 0.61462549, 0.90082079, 0.26507202],
       [0.43182936, 0.34033707, 0.06432396, 0.70808021]])

In [79]:
np.random.randint(10,50)

35

In [78]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1,"\n",arr2)

arr = np.concatenate((arr1,arr2))
arr

[1 2 3] 
 [4 5 6]


array([1, 2, 3, 4, 5, 6])

In [81]:
# 2-D
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(5,9).reshape(2,2)
print(arr1,"\n\n",arr2)

[[1 2]
 [3 4]] 

 [[5 6]
 [7 8]]


In [82]:
arr = np.concatenate((arr1,arr2), axis = 1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [83]:
arr = np.concatenate((arr1,arr2), axis = 0)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [84]:
arr = np.arange(1,7)

newarr = np.array_split(arr,2)

newarr

[array([1, 2, 3]), array([4, 5, 6])]

In [85]:
arr = np.arange(1,7)

newarr = np.array_split(arr,3)

newarr

[array([1, 2]), array([3, 4]), array([5, 6])]

In [86]:
import webbrowser

webbrowser.open("http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs")

True

In [87]:
import pandas as pd