# Yuhe Wu
# week11 - 2021/11/02 - 2021/11/04
# Python numpy: creating, processing, transporting arrays

In [1]:
import numpy as np

In [2]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8]])

print(arr_2d)
print(arr_2d.ndim)
print(arr_2d.shape)
print(arr_2d.dtype)

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)
int32


In [3]:
arr_1d = np.zeros(10)
print(arr_1d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
print(arr_1d.ndim)
print(arr_1d.dtype)

1
float64


In [5]:
arr_2d = np.zeros((5,5))
print(arr_2d)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
print(arr_2d.ndim)
print(arr_2d.dtype)

2
float64


In [7]:
arr_2d = np.ones((5,5))
print(arr_2d)
print(arr_2d.ndim)
print(arr_2d.dtype)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
2
float64


In [8]:
arr_1d = np.ones(10)
print(arr_1d)
print(arr_1d.ndim)
print(arr_1d.dtype)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
1
float64


In [9]:
arr_2d = np.empty((4,4))


print(arr_2d)
print(arr_2d.ndim)
print(arr_2d.dtype)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 8.90104239e-307]
 [1.33511969e-306 8.34441742e-308 1.78022342e-306 6.23058028e-307]
 [9.79107872e-307 6.89807188e-307 7.56594375e-307 6.23060065e-307]
 [1.78021527e-306 8.34454050e-308 1.11261027e-306 2.04712907e-306]]
2
float64


In [10]:
arr_2d = np.empty((2,2))

print(arr_2d)
print(arr_2d.ndim)
print(arr_2d.dtype)

[[4.24399158e-314 8.48798317e-314]
 [1.27319747e-313 1.69759663e-313]]
2
float64


In [11]:
arr_2d = np.empty((2,2),dtype=int)


print(arr_2d)
print(arr_2d.ndim)
print(arr_2d.dtype)

[[16843009 16843009]
 [16843009 16843009]]
2
int32


In [12]:
# arange
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [14]:
arr = np.arange(10,100,5)

print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.dtype)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
(18,)
1
int32


In [15]:
# reshape an array
# 1-d to 2d
print(arr)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [16]:
arr_2d = arr.reshape(3,6)
print(arr_2d)

[[10 15 20 25 30 35]
 [40 45 50 55 60 65]
 [70 75 80 85 90 95]]


In [17]:
arr_2d = arr.reshape(6,3)
print(arr_2d)

[[10 15 20]
 [25 30 35]
 [40 45 50]
 [55 60 65]
 [70 75 80]
 [85 90 95]]


In [18]:
arr_2d = arr.reshape(9,2)
print(arr_2d)

[[10 15]
 [20 25]
 [30 35]
 [40 45]
 [50 55]
 [60 65]
 [70 75]
 [80 85]
 [90 95]]


In [19]:
arr_2d = arr.reshape(2,9)
print(arr_2d)

[[10 15 20 25 30 35 40 45 50]
 [55 60 65 70 75 80 85 90 95]]


In [20]:
# 1d to 3d
arr = np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [21]:
arr_3d = arr.reshape(2,3,2)
print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [22]:
arr_3d = arr.reshape(2,2,3)
print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [23]:
arr_2d = arr.reshape(4,3)
print(arr_2d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [24]:
arr_2d = arr.reshape(4,4)
print(arr_2d)

ValueError: cannot reshape array of size 12 into shape (4,4)

In [25]:
arr = np.array([1,2,3,4,5,6,7,8])

arr_3d = arr.reshape(2,2,-1)

print(arr_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [26]:
arr_3d = arr.reshape(2,1,-1)

print(arr_3d)

[[[1 2 3 4]]

 [[5 6 7 8]]]


In [27]:
# iterating arrays
# 1-d
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [28]:
for n in arr:
    print(n)

0
1
2
3
4
5
6
7
8
9


In [29]:
arr_2d = np.arange(1,13).reshape(3,4)
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [30]:
for n in arr_2d:
    for i in n:
        print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [31]:
arr_3d = np.arange(1,13).reshape(2,3,2)
arr_3d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [32]:
for n in arr_3d:
    for i in n:
        for a in i:
            print(a)

1
2
3
4
5
6
7
8
9
10
11
12


In [33]:
# nditer
for n in np.nditer(arr_3d):
    print(n)

1
2
3
4
5
6
7
8
9
10
11
12


In [34]:

for n in np.nditer(arr_2d):
    print(n)

1
2
3
4
5
6
7
8
9
10
11
12


In [35]:
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [36]:
print(arr_2d[:,:2])

[[ 1  2]
 [ 5  6]
 [ 9 10]]


In [37]:
print(arr_2d[:,::2])

[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [38]:
# ndenumerate
arr = np.arange(1,13)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [39]:
for i,n in np.ndenumerate(arr):
    print(i,n)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6
(6,) 7
(7,) 8
(8,) 9
(9,) 10
(10,) 11
(11,) 12


In [40]:
for indx, n in np.ndenumerate(arr_2d):
    print(indx,n)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(2, 0) 9
(2, 1) 10
(2, 2) 11
(2, 3) 12


In [41]:
arr_2d * arr_2d

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [42]:
arr_2d + arr_2d

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [43]:
arr_2d - arr_2d

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [44]:
arr_2d **2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]], dtype=int32)

In [45]:
arr_2d **3

array([[   1,    8,   27,   64],
       [ 125,  216,  343,  512],
       [ 729, 1000, 1331, 1728]], dtype=int32)

In [46]:
1 / arr_2d

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.2       , 0.16666667, 0.14285714, 0.125     ],
       [0.11111111, 0.1       , 0.09090909, 0.08333333]])

In [48]:
import numpy as np
arr = np.arange(1,13,1)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [49]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [50]:
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [51]:
arr[5:]

array([ 6,  7,  8,  9, 10, 11, 12])

In [52]:
arr[0:6] = 100

In [53]:
arr

array([100, 100, 100, 100, 100, 100,   7,   8,   9,  10,  11,  12])

In [54]:
arr_2d = np.array([ [5,10,25],[15,10,20],[20,30,25]])
print(arr_2d.shape)
print(arr_2d.ndim)
print(arr_2d)

(3, 3)
2
[[ 5 10 25]
 [15 10 20]
 [20 30 25]]


In [55]:
arr_2d[1]

array([15, 10, 20])

In [56]:
arr_2d[1,0]

15

In [57]:
arr_2d[:2,1:]

array([[10, 25],
       [10, 20]])

In [58]:
arr_2d[2,-1]

25

In [59]:
arr_2d[1] = -1

In [60]:
arr_2d

array([[ 5, 10, 25],
       [-1, -1, -1],
       [20, 30, 25]])

In [63]:
arr_2d = np.zeros((9,9))
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [64]:
arr_2d.shape

(9, 9)

In [65]:
r = arr_2d.shape[0]
r

9

In [66]:
c = arr_2d.shape[1]
c

9

In [67]:
for idx in range(r):
    arr_2d[idx] = 10
    
arr_2d

array([[10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.]])

In [68]:
for idx in range(r):
    arr_2d[idx] = idx *2
    
arr_2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14.],
       [16., 16., 16., 16., 16., 16., 16., 16., 16.]])

In [69]:
arr_2d[1:7]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12.]])

In [70]:
arr_2d[1:7,3:6]

array([[ 2.,  2.,  2.],
       [ 4.,  4.,  4.],
       [ 6.,  6.,  6.],
       [ 8.,  8.,  8.],
       [10., 10., 10.],
       [12., 12., 12.]])

In [71]:
arr_2d[::2,3:6]

array([[ 0.,  0.,  0.],
       [ 4.,  4.,  4.],
       [ 8.,  8.,  8.],
       [12., 12., 12.],
       [16., 16., 16.]])

In [72]:
arr_2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14.],
       [16., 16., 16., 16., 16., 16., 16., 16., 16.]])

In [73]:
arr_2d[[1,6,7]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14.]])

In [75]:
arr_2d[[3,5]]

array([[ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.]])

In [79]:
arr_2d[:,[3,5]]

array([[ 0.,  0.],
       [ 2.,  2.],
       [ 4.,  4.],
       [ 6.,  6.],
       [ 8.,  8.],
       [10., 10.],
       [12., 12.],
       [14., 14.],
       [16., 16.]])

In [80]:
arr_2d[1:5,[3,5]]

array([[2., 2.],
       [4., 4.],
       [6., 6.],
       [8., 8.]])

In [81]:
# .T or self.transpose()

a = np.array([ [2,3],[4,5]])
a

array([[2, 3],
       [4, 5]])

In [82]:
a.T

array([[2, 4],
       [3, 5]])

In [83]:
arr_2d = np.arange(45).reshape(9,5)

In [84]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

In [85]:
arr_T = arr_2d.T
arr_T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44]])

In [86]:
np.dot(arr_2d,arr_T)

array([[  30,   80,  130,  180,  230,  280,  330,  380,  430],
       [  80,  255,  430,  605,  780,  955, 1130, 1305, 1480],
       [ 130,  430,  730, 1030, 1330, 1630, 1930, 2230, 2530],
       [ 180,  605, 1030, 1455, 1880, 2305, 2730, 3155, 3580],
       [ 230,  780, 1330, 1880, 2430, 2980, 3530, 4080, 4630],
       [ 280,  955, 1630, 2305, 2980, 3655, 4330, 5005, 5680],
       [ 330, 1130, 1930, 2730, 3530, 4330, 5130, 5930, 6730],
       [ 380, 1305, 2230, 3155, 4080, 5005, 5930, 6855, 7780],
       [ 430, 1480, 2530, 3580, 4630, 5680, 6730, 7780, 8830]])

In [90]:
a_t = a.T
a_t

array([[2, 4],
       [3, 5]])

In [91]:
np.dot(a,a_t)

array([[13, 23],
       [23, 41]])

In [92]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [94]:
a_t = np.transpose(a)
a_t

array([[0, 3],
       [1, 4],
       [2, 5]])

In [95]:
np.dot(a,a_t)

array([[ 5, 14],
       [14, 50]])

In [98]:
#swapaxes

a = np.array([[1,2,3]])
print(a,a.shape)

[[1 2 3]] (1, 3)


In [99]:
a.swapaxes(0,1)

array([[1],
       [2],
       [3]])

In [101]:
arr_3d = np.arange(45).reshape(3,5,3)
print(arr_3d,arr_3d.shape)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]]] (3, 5, 3)


In [102]:
a = arr_3d.swapaxes(1,2)
print(a)

[[[ 0  3  6  9 12]
  [ 1  4  7 10 13]
  [ 2  5  8 11 14]]

 [[15 18 21 24 27]
  [16 19 22 25 28]
  [17 20 23 26 29]]

 [[30 33 36 39 42]
  [31 34 37 40 43]
  [32 35 38 41 44]]]


In [103]:
a.shape

(3, 3, 5)