# Yuhe Wu
# week11: 2021/11/04
# python numpy universal functions

In [1]:
# zip()

import numpy as np

lst1 = [1,2,3,4,5,6,7,8,9]
lst2 = [11,12,13,14,15,16,17,18,19]

z = list(zip(lst1,lst2))
z

[(1, 11),
 (2, 12),
 (3, 13),
 (4, 14),
 (5, 15),
 (6, 16),
 (7, 17),
 (8, 18),
 (9, 19)]

In [2]:
z = []

for i,j in zip(lst1,lst2):
    z.append(i + j)
    
z

[12, 14, 16, 18, 20, 22, 24, 26, 28]

In [3]:
fname = ("Alice", "Bob", "Christy")
lname = ("Charlie", "Clark", "Robert")

flname = zip(fname,lname)
print(tuple(flname))

(('Alice', 'Charlie'), ('Bob', 'Clark'), ('Christy', 'Robert'))


In [4]:
arr = np.arange(21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [5]:
# sqrt
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [6]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08])

In [7]:
# randn
arr1 = np.random.randn(10)
arr1

array([ 0.35105224, -1.35961129,  0.52180187, -0.03687552,  0.38287709,
       -0.57767306,  0.97764209,  0.29943105,  0.35400921, -2.08030228])

In [9]:
arr2 = np.random.randn(10)
arr2

array([ 1.04930435, -0.03089234,  0.97716278, -0.56609525,  0.66789212,
        0.69591761,  0.24324496,  0.9472796 ,  1.22928454,  0.8540989 ])

In [10]:
np.add(arr1,arr2)

array([ 0.4707463 ,  0.43341011,  0.47322814, -0.42061157,  0.41578582,
        1.80975719,  0.38001648, -0.50042724, -0.21987736,  0.57764305])

In [13]:
np.maximum(arr1,arr2)

array([1.04930435, 0.46430245, 0.97716278, 0.14548368, 0.66789212,
       1.11383958, 0.24324496, 0.9472796 , 1.22928454, 0.8540989 ])

In [14]:
arr1 = np.arange(9).reshape(3,3)
arr2 = np.ones(9).reshape(3,3)

In [15]:
print(arr1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
print(arr2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
np.add(arr1,arr2)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [18]:
# array filtering
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
print(arr > 4)

[[False False False]
 [False False  True]
 [ True  True  True]]


In [21]:
# using where

np.where(arr < 4, 0,1)

array([[0, 0, 0],
       [0, 1, 1],
       [1, 1, 1]])

In [22]:
np.where((arr < 4) & (arr > 2), 0,1)

array([[1, 1, 1],
       [0, 1, 1],
       [1, 1, 1]])

In [23]:
arr1 = np.array([1,2,3,4,5])
arr2 = arr1 * 10

arr_b = np.array([True,False,True,True,False])

print(arr1)
print(arr2)
print(arr_b)
print(list(zip(arr1,arr2,arr_b)))

[1 2 3 4 5]
[10 20 30 40 50]
[ True False  True  True False]
[(1, 10, True), (2, 20, False), (3, 30, True), (4, 40, True), (5, 50, False)]
