# Yuhe Wu
# week10: 2021/10/28
# Python Numpy Processing

In [1]:
import numpy as np

In [2]:
my_list = [11,22,33,44,55,66,77]

arr_1d = np.array(my_list)
print(arr_1d)

[11 22 33 44 55 66 77]


In [3]:
print(arr_1d.dtype)

int32


In [4]:
fruits = ['Orange','Apple','Cherry','Grape']

arr_fruits = np.array(fruits)
print(arr_fruits)
print(arr_fruits.dtype)

['Orange' 'Apple' 'Cherry' 'Grape']
<U6


In [5]:
d = ['Orange','Apple','Cherry','Grape',1,2,3,4,5, [6,7,8,9,10]]

In [6]:
arr_d = np.array(d)

In [7]:
print(arr_d)

['Orange' 'Apple' 'Cherry' 'Grape' 1 2 3 4 5 list([6, 7, 8, 9, 10])]


In [8]:
print(arr_d.dtype)

object


In [9]:
arr_1d = np.array([1,2,3,4,5,6], dtype='i4')

In [10]:
print(arr_1d.dtype)

int32


In [11]:
arr_1d = np.array([1,2,3,4,5,6], dtype='i8')
print(arr_1d.dtype)

int64


In [12]:
arr_1d = np.array([1,2,3,4,5,6], dtype='S')
print(arr_1d)
print(arr_1d.dtype)

[b'1' b'2' b'3' b'4' b'5' b'6']
|S1


In [13]:
my_arr = np.array(['1','2','3','4','5'], dtype = 'i8')

In [14]:
print(my_arr)
print(my_arr.dtype)

[1 2 3 4 5]
int64


In [15]:
scores = [78.5,88.9,90.3,89.9]

my_arr = np.array(scores)
print(my_arr)

[78.5 88.9 90.3 89.9]


In [16]:
arr = my_arr.astype('i')

In [17]:
print(arr)

[78 88 90 89]


In [18]:
arr = np.array([1,0,0,3,4,5,6,7,0])

In [19]:
print(arr,arr.dtype)

[1 0 0 3 4 5 6 7 0] int32


In [20]:
arr_bool = arr.astype(bool)

In [21]:
print(arr_bool)

[ True False False  True  True  True  True  True False]


In [23]:
# Numpy Array Copy vs View

lst1 = [1,2,3,4,5]
lst2 = [11,22,33,44,55]

my_list = [lst1,lst2]
print(my_list)

[[1, 2, 3, 4, 5], [11, 22, 33, 44, 55]]


In [24]:
arr = np.array(my_list)
print(arr)

[[ 1  2  3  4  5]
 [11 22 33 44 55]]


In [25]:
print(arr.ndim)

2


In [26]:
arr_copy = arr.copy()
print(arr_copy)

[[ 1  2  3  4  5]
 [11 22 33 44 55]]


In [27]:
print(arr)

[[ 1  2  3  4  5]
 [11 22 33 44 55]]


In [28]:
arr[1,0] = 99

In [29]:
print(arr)

[[ 1  2  3  4  5]
 [99 22 33 44 55]]


In [30]:
print(arr_copy)

[[ 1  2  3  4  5]
 [11 22 33 44 55]]


In [32]:
# View view is just a view of the priginal array
arr_view = arr.view()
print(arr_view)

[[ 1  2  3  4  5]
 [99 22 33 44 55]]


In [33]:
arr[0,0] = 10

In [34]:
print(arr)

[[10  2  3  4  5]
 [99 22 33 44 55]]


In [35]:
print(arr_view)

[[10  2  3  4  5]
 [99 22 33 44 55]]


In [37]:
print(arr_copy.base)
print(arr_view.base)

None
[[10  2  3  4  5]
 [99 22 33 44 55]]


In [38]:
# Shape of the Array
print(arr)

[[10  2  3  4  5]
 [99 22 33 44 55]]


In [39]:
print(arr.ndim)
print(arr.shape)

2
(2, 5)


In [40]:
arr_5d = np.array([1,2,3,4,5],ndmin=5)

In [41]:
print(arr_5d)

[[[[[1 2 3 4 5]]]]]


In [44]:
print(arr_5d.ndim)
print(arr_5d.shape)
print(arr_5d.shape[0])

5
(1, 1, 1, 1, 5)
1
