# Yuhe Wu
# week10: 2021/10/26 - 2021/10/28
# Python Numpy Intro

In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.5'

In [3]:
arr = np.array([1,2,3,4,5,6])

In [4]:
arr

array([1, 2, 3, 4, 5, 6])

In [5]:
type(arr)

numpy.ndarray

In [6]:
# dimensions in arrays
# 0-D Arrays

In [7]:
arr_0d = np.array(50)
arr_0d

array(50)

In [8]:
print(arr_0d)

50


In [9]:
# 1-D Array
arr_1d = np.array([1,2,3,4,5,6,7,8])
arr_1d

array([1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
# 2-D array matrix
arr_2d = np.array([ [1,2,3,4,5], [6,7,8,9,10]])
print(arr_2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [11]:
# 3-D array
arr_3d = np.array([ [  [1,2,3], [4,5,6]  ],[  [7,8,9],[10,11,12]  ]   ])

In [12]:
print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [13]:
# numpy arry ndim attribute
print(arr_0d.ndim)

0


In [14]:
print(arr_3d.ndim)

3


In [15]:
print(arr_1d.ndim)

1


In [16]:
print(arr_2d.ndim)

2


In [17]:
print(arr_0d.ndim , arr_1d.ndim , arr_2d.ndim , arr_3d.ndim)

0 1 2 3


In [18]:
# create an array with a certain dimention
# 4-D
arr_4d = np.array([1,2,3,4,5],ndmin=4)
print(arr_4d)

[[[[1 2 3 4 5]]]]


In [19]:
print(arr_4d.ndim)

4


In [20]:
arr_5d = np.array([1,2,3,4,5],ndmin=5)
print(arr_5d)
print(arr_5d.ndim)

[[[[[1 2 3 4 5]]]]]
5


In [21]:
# indexing and slicing
'''

arr[start:end:step]
start: start index
end: stop index (exclusive)
step: a jump, step is considered 1

'''

print(arr_1d)

[1 2 3 4 5 6 7 8]


In [22]:
arr_1d[2]

3

In [23]:
arr_1d[-1]

8

In [24]:
print(arr_1d[1] + arr_1d[4])

7


In [25]:
# access 2-D array
print(arr_2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [26]:
arr_2d[0,1]

2

In [27]:
arr_2d[1,3]

9

In [28]:
# 3-D array
print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [29]:
arr_3d[0,1,1]

5

In [30]:
arr_3d[1,1,2]

12

In [31]:
arr_3d[1,1,-1]

12

In [32]:
# Array slicing
#slicing 1-D arrays
print(arr_1d)

[1 2 3 4 5 6 7 8]


In [33]:
print(arr_1d[1:3])

[2 3]


In [34]:
print(arr_1d[3:])

[4 5 6 7 8]


In [35]:
print(arr_1d[:-1])

[1 2 3 4 5 6 7]


In [36]:
print(arr_1d[-3:-1])

[6 7]


In [37]:
#slicing 2-D array
print(arr_2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [38]:
print(arr_2d[1,-1])

10


In [39]:
print(arr_2d.ndim)

2


In [40]:
print(arr_2d[0,1:3])

[2 3]


In [41]:
print(arr_2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [44]:
print(arr_2d[0:2,2 ])

[3 8]


In [46]:
print(arr_2d[:,2 ])

[3 8]


In [47]:
print(arr_2d[0:2,3: ])

[[ 4  5]
 [ 9 10]]


In [50]:
print(arr_2d[1,2:])

[ 8  9 10]


In [51]:
#3-D arrays
print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [53]:
print(arr_3d[0,1,1])

5


In [57]:
print(arr_3d[1,1,0])

10


In [58]:
print(arr_3d[0,1,1:3])

[5 6]


In [59]:
print(arr_3d[1,:,0:2])

[[ 7  8]
 [10 11]]
