In [1]:
import numpy as np
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
a[0] = a[0,::-1]
a[:,1]=a[::-1,1]

In [2]:
a

array([[ 5,  7,  3,  2,  1],
       [ 6,  4,  8,  9, 10]])

In [3]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]])
print(a[0,1], a[1,2], a[0,2])

2 6 3


In [4]:
import numpy as np 
a = np.zeros((2,2))
b = np.eye(2)

In [5]:
a

array([[0., 0.],
       [0., 0.]])

In [6]:
b

array([[1., 0.],
       [0., 1.]])

In [7]:
import numpy as np 
a = np.matrix([[1, 0], [2, -1]])
r = a * a

In [8]:
r

matrix([[1, 0],
        [0, 1]])

In [9]:
import numpy as np 

b = np.mat([[5, 6], [7, 8]])

In [10]:
b

matrix([[5, 6],
        [7, 8]])

In [11]:
type(b)

numpy.matrix

In [12]:
import numpy as np 
a = np.array([[1, 1], [2, 0]])
b = np.matrix(a)
I = np.identity(2)
x = a * I
y = b * I


In [13]:
x

array([[1., 0.],
       [0., 0.]])

In [14]:
y

matrix([[1., 1.],
        [2., 0.]])

In [15]:
import numpy as np
a = np. array([ [1, 2], [3, 4] ]) 
print(np.mean(a, axis=None)== np.mean(a))

True


In [16]:
import numpy as np 
a = np.ones(2)
b = np.ones((1,2))

In [17]:
a

array([1., 1.])

In [18]:
b

array([[1., 1.]])

In [19]:
import numpy as np
a = np.array([[1,2,3], [4,5,6]])
b = a.T

In [20]:
b

array([[1, 4],
       [2, 5],
       [3, 6]])

In [21]:
import numpy as np
a = np. array([ [1, 2], [3, 4] ])
print(round(np.var(a),2) == round(np.std(a)**2,2))

True


In [22]:
a = np.array([[10, 11, 12]])
b = np.array([[20], [21], [22]])
c = np.array([[1,2], [3,4], [5,6]])
print(a.shape, b.shape, c.shape)

(1, 3) (3, 1) (3, 2)


In [23]:
import numpy as np
a = np.array( [[1,2, 3, 4],  [5,6, 7, 8],  [9,10,11,12]] )
b = a[1:3, 2:]

In [24]:
b

array([[ 7,  8],
       [11, 12]])

In [25]:
import numpy as np
a = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
a[-1,-1] = 0
a[a.shape[0]-2, 1] = a[0, -1] + a[-1, 0]
a[0,0]= a[0,2] + a[2,0]

In [26]:
a

array([[10,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  0]])

In [27]:
import numpy as np 

a = np.zeros((2,2))

b = np.eye(2)


In [28]:
a

array([[0., 0.],
       [0., 0.]])

In [29]:
b

array([[1., 0.],
       [0., 1.]])

In [30]:
import numpy as np
a = np.array([[1,2], [3,4]])
#A list comprehension 
b = [a[j,i] for i in range(a.shape[0]) for j in range(a.shape[1])]

In [31]:
b

[1, 3, 2, 4]

In [33]:
import numpy as np
a = np.array([[1,2, 3], [4,5,6]]) 
b = a.reshape(-1)

In [34]:
b

array([1, 2, 3, 4, 5, 6])

In [35]:
import numpy as np

a = np.random.random((2,2))

In [36]:
a

array([[0.97875966, 0.16669892],
       [0.14477712, 0.5505913 ]])

In [37]:
import numpy as np
a = np.array([1,2, 3, []]) 
a[-1].append(4)
a[-1].append(5)
print(len(a))

4


In [38]:
import numpy as np 
a = np.array([[1, 0], [2, -1]])
r = a * a

In [39]:
r

array([[1, 0],
       [4, 1]])

In [40]:
import numpy as np 
a = np.array([[1, 1], [2, 0]])
b = np.matrix(a)
I = np.identity(2)
x = a * I
y = b * I

In [41]:
x

array([[1., 0.],
       [0., 0.]])

In [42]:
y

matrix([[1., 1.],
        [2., 0.]])